### ISSUE TITLE
Failed to invoke HPO workbench on Mac OS X 10.12.6

### ISSUE THREAD

**Issue by djinnome** [TheJacksonLaboratory/HPOworkbench#48]
Hi there,

I am interested in using the HPO workbench, but when I tried to download the jar, I got the following error message:

```
bash$ java -jar ~/Downloads/HpoWorkbench.jar 
Error: Could not find or load main class org.monarchinitiative.hpoworkbench.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application
```

This is the version of java I have:

```
bash$ java -version
openjdk version "11.0.1" 2018-10-16
OpenJDK Runtime Environment 18.9 (build 11.0.1+13)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.1+13, mixed mode)
```

**Comment by pnrobinson** [comment]
Java has been changed a lot from version 8 (which we wrote the app under) and version 11, and this is the reason (Java 11 does not include the GUI library javaFX and this needs to be separately included, together with a few other changes). There are some more or less annoying ways to install two versions of Java on Mac. We are planning on upgrading a lot of our software to Java 11 this year, but want to wait a little bit because it seems most people are still using Java 8.

I will leave this issue open as a reminder to go to Java 11, but I do not think we can do so in the next month, sorry.

**Comment by pnrobinson** [comment]
Coming back to this there are multiple issues we are trying to address to move from Java 8 to Java 11 (or indeed Java 13, which was released last week). Some of the issues relate to external libraries that themselves are difficult to run in Java 11. So I am afraid the only possibility right now is to run from Java 8. ODK does not seem to do as good a job as Oracle Java 8 with Java FX.
