### ISSUE TITLE
Covered buttons

### ISSUE THREAD

**Issue by hekselman** [TheJacksonLaboratory/HPOworkbench#53]
1) When opening the JAVA file one my computer, I cant see some of the buttons (on the bottom right), because they are covered the "All resources set!" message. It happens even when I try to resize the window.
2) I can also see that some of the "check circles" don't have a description, but rather have "..." instead. Is this suppose to happen?
Thanks in advance.

**Comment by pnrobinson** [comment]
Not sure without seeing a picture but probably you could increase the size of the window. The all resources set message is on the bottom left and so if it is on the bottom right on your computer something might be going wrong. Can you restart and if the problem persists could you upload a screen shot of what you are seeing?

**Comment by hekselman** [comment]
![image](https://user-images.githubusercontent.com/37185814/80362574-887dd100-888b-11ea-9198-cb0288342cb6.png)

**Comment by pnrobinson** [comment]
I see -- this is because the app requires a certain minimum screen size. If you cannot increase the screen size more on the current device, then I am afraid there is nothing more to be done, except perhaps increase the screen resolution or more to another computer. Most of the functionality should be accessible though!
