### ISSUE TITLE
Unable to Download HPO annotations from HPOworkbench

### ISSUE THREAD

**Issue by Sokanha** [TheJacksonLaboratory/HPOworkbench#59]
Hello,

I want to use HPOworkbench for my research and I just downloaded the workbench v.1.6.1 today. However, I tried downloading HPO annotations from the edit tab for many times but nothing changes. Please find the screenshot below.

![image](https://user-images.githubusercontent.com/81195755/113597930-5268d580-9634-11eb-980f-cdbbd3f8107d.png)

Could you please advise on how I can resolve this?

Thank you!
Sokanha

**Comment by pnrobinson** [comment]
Did you see any log messages on the command line? 
Or could you send your log file?
Note that this tool is not highly polished (we never published it), it is still a bit rough around the edges.

**Comment by e-lbtn** [comment]
Hello,

I have the same problem as Sokanha ... No message appears when I request the download of HPO annotations. At the same time, I think the download of the HPO ontology works because I have access to the data in the "statistics" part. I also tried importing a copy, but it doesn't work.

Could the problem come from my computer and more precisely from a dysfunction with java? Or is it a direct issue with downloading the HPO annotations?

Thank you!

Emeline

**Comment by pnrobinson** [comment]
@Sokanha @e-lbtn I have updated the code and it should work now -- please download the latest release. The problem was that the location of a file had changed. Please reopen this issue if the problem persists.

**Comment by Sokanha** [comment]
Thanks so much @pnrobinson for your help! I need to re-download everything again but it works now.
